.github/workflows/make.yml, manifest.yml, services/terraform/eks-provision.tf
These commits resolve problems I've observed tripping up clean apply/destroy operations when the brokerpak was in use in a prod-like environment.
=> Minimize chances of a blocker halfway through provisioning

.github/workflows/make.yml
Turns out it really only wants branch names, not refs here. Merging this will cause a new release to be cut as expected.
=> Fix ref to only include the branch name here

manifest.yml, services/terraform/eks-provision.tf
Here's an example of the intermittent problem we're trying to resolve:
Note this part of the error message in particular:
`Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials on .terraform/modules/instance.aws_load_balancer_controller/main.tf line 384, in resource "helm_release" "using_iamserviceaccount"`
My hypothesis is that the by the time the Fargate profile is set up and coredns has been fully restarted (which can take several minutes), the token generated via `data.aws_eks_cluster_auth.main` has expired. That expired token is then used to initialize the Helm provider when the first `helm_resource` is deployed, resulting in the error.
It turns out [there's documentation about this problem, and a facility for addressing …
=> Ensure that k8s and helm providers are using a valid token

.github/workflows/make.yml
Cuts out an hour of testing time post-merge and pre-release
=> Test only on PRs, not on pushes to main

Makefile, manifest.yml, services/eks-service-definition.yml, services/terraform/eks-bind.tf, services/terraform/eks-provision.tf
When a provisioned cluster is bound, a namespace is created along with an "admin" service account with full permissions in that namespace. The binding output contains a kubeconfig suitable for working with that namespace via the service account.
Addresses https://github.com/GSA/eks-brokerpak/issues/5
=> Bind creates namespace

manifest.yml, services/eks-service-definition.yml, services/terraform/eks-bind.tf, services/terraform/eks-provision.tf, services/terraform/test-provision/2048_fixture.yml
Use [the provided names and tags](https://github.com/cloudfoundry-incubator/cloud-service-broker/blob/master/docs/brokerpak-specification.md#provision) during provisioning and binding. 
This will help us create a findable "solr" k8s cluster when the broker is deployed. Then the Terraform for the Solr brokerpak can refer to it using a data source and use that cluster by default, unless k8s access details are explicitly provided.
=> Better naming and tagging

manifest.yml, services/terraform/eks-bind.tf, services/terraform/eks-provision.tf
There's a 32 character limit for prefixes on the AWS side, and CF sometimes supplies UUIDs for instanceids.
=> Ensure all cluster names are short enough

manifest.yml, services/terraform/eks-provision.tf
When we create a binding, we set up a dedicated admin ServiceAccount for that namespace. We don't give out cluster-admin permissions. However, the operators need to create CRDs, which can only be done at the cluster-admin level. So now we install the operators as part of the base k8s deployment.
This also simplifies use of the Solr brokerpak... One can just create `solr-cloud` services without worrying about whether someone has already created a `solr-operator` in the underlying k8s.
=> Install zookeeper-operator and solr-operator Helm charts

manifest.yml, services/terraform/eks-bind.tf, services/terraform/eks-provision.tf
* Auto-generated input IDs sometimes start with numbers or are longer than are allowed. Hashing and limiting their length ensures we don't randomly see failures when this happens.
* Tokens, when they exist outside a kubeconfig file, are expected to be base64-encoded. That's also coincidentally how our datagov-brokerpak expects them to be passed in. ;)
=> Make safe names and tokens

.env.secrets-template, .github/workflows/release.yml, .github/workflows/test.yml, Makefile, README.md, eks-service-definition.yml, examples.json, manifest.yml, terraform/provision/2048_fixture.yml, terraform/provision/crds.tf, terraform/provision/eks.tf, terraform/provision/external-dns.tf, terraform/provision/ingress.tf, terraform/provision/rbac.tf, terraform/provision/variables.tf, terraform/provision/vpc.tf, test.sh
Addresses https://github.com/GSA/eks-brokerpak/issues/7
- Upgrade EKS to 1.19 and make the fixture use the final networking API v1
- Add a role with a policy sufficient to edit entries in Route53
- Add a service account that can assume that role
- Give the service account access to watch all the APIs it needs
- Add the external-dns helm chart, and configure it to use that service account
- Set ingress_nginx to configure all ingresses to point to the ALB that points to it
=> Add external DNS for each Ingress

.github/workflows/test.yml, README.md, terraform/provision/crds.tf, terraform/provision/ingress.tf
- Sort annotations to 🤞  reduce merge conflicts
- Use a TLS 1.2-only ALB policy.
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html
=> Strict TLS 1.2 support for ALBs

Makefile, eks-service-definition.yml, terraform/bind/data.tf, terraform/bind/variables.tf, terraform/provision/eks.tf, terraform/provision/external-dns.tf, terraform/provision/ingress.tf, terraform/provision/outputs.tf, terraform/provision/variables.tf, terraform/provision/vpc.tf
This will destroy existing k8s clusters to replace them with more random names. However, from here out the specified subdomain is *only* used for DNS, which makes it easier to change the name and avoid collisions in future.
=> Non destructive renaming

terraform/provision/ingress.tf
Lack of TLS here was blocking nginx-ingress from injecting HSTS headers
Addresses https://github.com/GSA/datagov-deploy/issues/3247
=> Change alb-to-nginx ingress to use TLS

terraform/provision/ingress.tf
See https://github.com/apache/solr-operator/issues/277
=> Use an ingress-nginx controller that still supports v1beta1 (needed by the solr-operator)

.gitignore, README.md, docs/instance-cleanup.md, eks-service-definition.yml, manifest.yml, terraform/bind/providers.tf, terraform/provision/Dockerfile, terraform/provision/README.md, terraform/provision/crds.tf, terraform/provision/eks.tf, terraform/provision/external-dns.tf, terraform/provision/ingress.tf, terraform/provision/logging.tf, terraform/provision/main.tf, terraform/provision/providers.tf, terraform/provision/rbac.tf, terraform/provision/terraform.tfvars-template, terraform/provision/variables.tf, terraform/provision/vpc.tf
Added instructions for iterating in the terraform/provision directory
Added instructions for cleaning up a botched service instance in AWS
Upgraded all the Terraform stuff:
* terraform, by a few patchlevels
* the AWS  provider, helm provider, kubernetes provider
* the EKS module
* the nginx-ingress chart
* the alb-controller helm chart
* the solr-operator and zookeeper-operator
* the manifest file used by the broker itself
=> Upgrade Terraform providers and modules

terraform/provision/crds.tf, terraform/provision/logging.tf
This is to enable use of datagov-brokerpak-solr 0.20.0 so that we can have auth-enabled Solr clusters.
=> Downgrade the solr-operator

terraform/provision/crds.tf
This is the version that the currently-supported solr-brokerpak needs.
=> Downgrade all the way to solr-operator 0.2.8

README.md, docs/instance-cleanup.md, eks-service-definition.yml, terraform/provision/eks.tf, terraform/provision/ingress.tf, terraform/provision/persistent-storage.tf, terraform/provision/variables.tf
Related to GSA/datagov-deploy#3677
New Additions:
- Add VPC CNI for EKS cluster
- Convert Application Load Balancer to Network Load Balancer
Upgrades:
- Update `AWS LB Controller` to 2.3
=> Update ALB Controller to provision NLBs

.github/workflows/test.yml, Makefile, eks-service-definition.yml, terraform/provision/eks.tf, terraform/provision/ingress.tf
This PR fixes [the problem where instances provisioned via the SSB time out while waiting for the ingress-nginx service to get an external IP](https://gsa-tts.slack.com/archives/C2N85536E/p1644996338677069?thread_ts=1644971323.182399&cid=C2N85536E).
As I mentioned in Slack:
> ...we've been bitten by this kind of thing before. I think we should alter our tests to use a 64-character instance ID so we'll find these problems before accepting PRs, rather than only after a long deployment process to get it in use by the SSB.
Feel free to make that change yourself before accepting this PR, or wait for me to do it tomorrow... Otherwise we can do it in another PR. I just need to get to bed now and wanted to get this in flight for the east-coast morning crew!
=> Avoid overlong LB names

.github/workflows/release.yml, .github/workflows/test.yml, .gitignore, Makefile, README.md, bin/binding-fetch.sh, bin/binding-wait.sh, bin/instance-wait.sh, eks-service-definition.yml, terraform/provision/crds.tf, terraform/provision/eks.tf, terraform/provision/external-dns.tf, terraform/provision/ingress.tf, terraform/provision/logging.tf, terraform/provision/persistent-storage.tf, terraform/provision/rbac.tf, test.sh
In case kubenetes tries to create the storage class before the cluster is actually functional (i.e. node groups coming up or some other race condition), wait until we know the cluster is more ready
Related to, 
```
Error: Error: Post "https://3ecc6d85ff42f6acfd57348528412984.gr7.us-west-2.eks.amazonaws.com/apis/storage.k8s.io/v1/storageclasses": dial tcp 100.20.251.29:443: i/o timeout  with kubernetes_storage_class.ebs-sc,  on persistent-storage.tf line 209, in resource "kubernetes_storage_class" "ebs-sc": 209: resource "kubernetes_storage_class" "ebs-sc" { exit status 1
```
=> Add dependency for sc on cluster-functional

terraform/provision/eks.tf
Relates to https://github.com/GSA/datagov-deploy/issues/3669
=> fix: use new names for managed node group size params

README.md, terraform/modules/provision-aws/eks.tf, terraform/modules/provision-aws/ingress.tf, terraform/modules/provision-k8s/k8s-network-policy.tf
Introduce dependencies that enable reliable `terraform destroy`.
Note the depends_on in k8s-network-policy.tf introduces an explicit dependency between code in the provision-aws and provision-k8s modules. See the comment on that commit for discussion.
Related to https://github.com/gsa/data.gov/issues/3617
=> Make `terraform destroy` reliable

README.md, docs/scanning-reports.md, eks-service-definition.yml, manifest.yml, terraform/modules/bind/versions.tf, terraform/modules/provision-aws/eks.tf, terraform/modules/provision-aws/versions.tf, terraform/modules/provision-k8s/k8s-scanning.tf, terraform/modules/provision-k8s/standalone-versions.tf, test.sh
Implements https://github.com/GSA/datagov-brokerpak-eks/issues/6
=> Scan all the things

eks-service-definition.yml, terraform/modules/provision-aws/eks.tf, terraform/modules/provision-aws/variables.tf, terraform/modules/provision-k8s/k8s-persistent-storage.tf
This allows users to specify that the entire workload should be run within a single AWS Availability Zone for latency or other operational requirements.
New Additions:
- Restrict Managed Node Group Node Creation to a single availability zone if `single_az = true`
- Change volume binding for storage class to `"WaitForFirstConsumer"` to ensure it can be attached to nodes with the correct topology (specifically, within the same availability zone)
This is not the most optimal solution (primarily just a quick workaround).  Things that must be considered long-term is auto-scaling specification to ensure new nodes are only created within the same existing availability zone and there aren't any other edge cases to consider.  By forcing the managed node group to live within a single subnet, it …
=> Single AZ Support

terraform/modules/provision-aws/locals/k8s-locals.tf, terraform/modules/provision-k8s/k8s-network-policy.tf, terraform/modules/provision-k8s/k8s-persistent-storage.tf, terraform/modules/provision-k8s/standalone-variables.tf, test.sh, test_specs/networkpolicy/allow_github.yml
Relates to https://github.com/GSA/data.gov/issues/3355
This PR uses the pre-existing calico setup to deploy a networkpolicy to allow only connections from cloud.gov into the EKS worker pods.  It was coupled with the default-deny-egress policy to have a single default configuration that users are allowed to modify without the broker wanting to undo the user's changes.
This replaces #52, but there is still some good documentation about VPC configuration in that PR.
Cool Additional References:
- Github posts all of it's IP address ranges at https://api.github.com/meta
- Terraform [`kubernetes_network_policy`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/network_policy)
- k8s [network policy](https://kubernetes.io/docs/concepts/services-networking/network- …
=> Restrict Ingress to Cloud.gov by default

eks-service-definition.yml, terraform/main.tf, terraform/modules/provision-aws/README.md, terraform/modules/provision-aws/eks.tf, terraform/modules/provision-aws/variables.tf, test.sh
Would supersede #94 (if successful)
This is a test to see if the tests will start if the same PR is from data.gov as opposed to from a fork.
=> Make GSA-Hardened AMI optional (copy)

README.md
cloudfoundry/cloud-service-broker renamed their trunk to `main` - this updates the links to match
=> Update README to point to current trunk
